<h3>HTML/CSS Ratios</h3>
<div class="code-wrap">
    <div class="code-lines"></div>
    <div class="code-icon" data-toggle="tooltip" data-placement="left" data-id="docu-ratios" title="Select code"><i class="fas fa-code" aria-hidden="true"></i></div>
    <pre><code id="docu-ratios" class="html">&lt;div id="canvas" class="canvas-ratio-21by9"&gt;
    &lt;!-- ... --&gt;
&lt;/div&gt;

&lt;div id="canvas" class="jca-ratio-16by9"&gt;
    &lt;!-- ... --&gt;
&lt;/div&gt;

&lt;div id="canvas" class="jca-ratio-4by3"&gt;
    &lt;!-- ... --&gt;
&lt;/div&gt;

&lt;div id="canvas" class="jca-ratio-2by1"&gt;
    &lt;!-- ... --&gt;
&lt;/div&gt;

&lt;div id="canvas" class="jca-ratio-1by1"&gt;
    &lt;!-- ... --&gt;
&lt;/div&gt;</code></pre>
</div>

<h3>JavaScript (Canvas Animation)</h3>
<div class="code-wrap">
    <div class="code-lines"></div>
    <div class="code-icon" data-toggle="tooltip" data-placement="left" data-id="docu-jca" title="Select code"><i class="fas fa-code" aria-hidden="true"></i></div>
    <pre><code id="docu-jca" class="javascript">$('#canvas').canvasAnimation({
    steps: [
        {
            addClass: '',    // adds one or more classes to #canvas ('foo bar' adds 2 classes)
            removeClass: '', // remove one or more classes from #canvas ('foo bar' removes 2 classes)
            duration: 500,   // duration of this step (milliseconds, default: 500)
            pause: false     // pause animation at this point (boolean, default: false)
        }
    ],
    timeout: 0, // 0 = starts immediately the first step (milliseconds)
    resetDuration: 500, // time it takes to reset all animations (milliseconds)
    infinite: true, // if true: plays animation infinite
    autoplay: true, // if true: plays animation instantly
    controls: true, // if true: adds controls to canvas
    editor: {
        enable: false, // if true: show editor on page
        wrapper: '.jca-editor-container' // editor wrapper class
    },
    useIcons: false, // use icons from an icon framework instead of css icons
    icons: {
        backward: '&lt;i class="fas fa-step-backward"&gt;&lt;/i&gt;',
        play: '&lt;i class="fas fa-play"&gt;&lt;/i&gt;',
        pause: '&lt;i class="fas fa-pause"&gt;&lt;/i&gt;',
        stop: '&lt;i class="fas fa-stop"&gt;&lt;/i&gt;',
        forward: '&lt;i class="fas fa-step-forward"&gt;&lt;/i&gt;',
        expand: '&lt;i class="fas fa-expand"&gt;&lt;/i&gt;',
        editor: '&lt;i class="fas fa-edit"&gt;&lt;/i&gt;'
    },
    controlsWrapper: '.jca-controls', // class of the controls wrapper
    backwardButton: '.jca-backward', // class of step backward button
    playButton: '.jca-play', // class of play button
    pauseButton: '.jca-pause', // class of pause button
    stopButton: '.jca-stop', // class of reset button
    forwardButton: '.jca-forward', // class of step forward button
    expandButton: '.jca-expand', // class of expand button
    editorButton: '.jca-editor', // class of edit button
    classDone: 'jca-done', // is set if the animation is done
    classWait: 'jca-wait', // is set if autoplay : false and animation is never played or user clicked on reset button
    classForward: 'jca-forward', // is set if user clicked forward
    classBackward: 'jca-backward', // is set if user clicked backward
    classWrap: 'jca-wrap',
    controlsTemplate:
        '&lt;div class="jca-controls"&gt;' +
            '&lt;div class="jca-backward"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-play"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-pause"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-stop"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-forward"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-expand"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-editor"&gt;&lt;/div&gt;' +
        '&lt;/div&gt;',
    onPlay: null, // called before first animation step
    onDone: null, // called after last animation step
    onWait: null  // called if classWait was added
});</code></pre>
</div>

<h3>JavaScript (Canvas Animation Editor)</h3>
<div class="code-wrap">
    <div class="code-lines"></div>
    <div class="code-icon" data-toggle="tooltip" data-placement="left" data-id="docu-jcae" title="Select code"><i class="fas fa-code" aria-hidden="true"></i></div>
    <pre><code id="docu-jcae" class="javascript">$('#canvas').canvasAnimationEditor({
    enable: false, // if true: show editor on page
    decimal: 2, // accuracy of numbers
    draggableItems: true, // jQuery UI Draggable is required for this feature
    wrapper: '.jca-editor-container', // editor wrapper class
    labels: {
        top: 'top',
        left: 'left',
        width: 'width',
        height: 'height',
        newItem: 'New: ',
        newItemBlank: 'Blank',
        newItemExt: 'Extended',
        select: 'Select: ',
        selectCss: 'CSS',
        selectHtml: 'HTML',
        remove: 'Remove: ',
        removeItem: 'Item',
        removeStyle: 'Style',
        className: 'CSS class name',
        parentWidth: 'Parent width in px',
        parentHeight: 'Parent height in px',
        itemWidth: 'Item width in px',
        itemHeight: 'Item height in px',
        itemTop: 'Item offset top in px',
        itemLeft: 'Item offset left in px',
        confirmAppendPrepend: 'OK = append item / Cancel = prepend item',
        confirmRemoveItem: 'Are you sure to remove item?',
        confirmRemoveStyle: 'Are you sure to remove style?',
        alertCanvasId: 'Canvas needs attribute "id".'
    },
    template: '&lt;div class="jca-editor-container"&gt;' +
        '&lt;div class="jca-container"&gt;' +
            '&lt;div class="jca-col jca-cord-dimension"&gt;' +
                '&lt;div class="jca-box"&gt;' +
                    '&lt;div class="jca-label jca-top"&gt;&lt;/div&gt;' +
                    '&lt;div class="jca-label jca-left"&gt;&lt;/div&gt;' +
                    '&lt;div class="jca-label jca-width"&gt;&lt;/div&gt;' +
                    '&lt;div class="jca-label jca-height"&gt;&lt;/div&gt;' +
                    '&lt;input type="number" step="0.01" name="jca_top" /&gt;' +
                    '&lt;input type="number" step="0.01" name="jca_left" /&gt;' +
                    '&lt;input type="number" step="0.01" name="jca_width" /&gt;' +
                    '&lt;input type="number" step="0.01" name="jca_height" /&gt;' +
                '&lt;/div&gt;' +
            '&lt;/div&gt;' +
            '&lt;div class="jca-col jca-selector-breadcrumb"&gt;&lt;/div&gt;' +
            '&lt;div class="jca-col jca-code-col"&gt;' +
                '&lt;div id="jca-html"&gt;&lt;/div&gt;' +
                '&lt;div id="jca-css"&gt;&lt;/div&gt;' +
            '&lt;/div&gt;' +
            '&lt;div class="jca-col jca-button-col"&gt;' +
                '&lt;span class="jca-new"&gt;&lt;/span&gt;&lt;input type="button" name="jca_new_item" value=""/&gt; &lt;input type="button" name="jca_new_item_ext" value=""/&gt;&lt;br/&gt;' +
                '&lt;span class="jca-select"&gt;&lt;/span&gt;&lt;input type="button" name="jca_html" value=""/&gt; &lt;input type="button" name="jca_css" value=""/&gt;&lt;br/&gt;' +
                '&lt;span class="jca-remove"&gt;&lt;/span&gt;&lt;input type="button" name="jca_remove_item" value=""/&gt; &lt;input type="button" name="jca_remove_style" value=""/&gt;&lt;br/&gt;&lt;br/&gt;' +
                '&lt;span class="jca-width"&gt;&lt;/span&gt; &lt;span class="jca-width-val"&gt;&lt;/span&gt; &lt;span class="jca-height"&gt;&lt;/span&gt; &lt;span class="jca-height-val"&gt;&lt;/span&gt;&lt;br/&gt;' +
                '&lt;span class="jca-top"&gt;&lt;/span&gt; &lt;span class="jca-top-val"&gt;&lt;/span&gt; &lt;span class="jca-left"&gt;&lt;/span&gt; &lt;span class="jca-left-val"&gt;&lt;/span&gt;' +
            '&lt;/div&gt;' +
        '&lt;/div&gt;' +
    '&lt;/div&gt;'
});</code></pre>
</div>