<div class="code-wrap">
    <div class="code-lines"></div>
    <i class="fas fa-code copy-code transition" aria-hidden="true" data-toggle="tooltip" data-placement="left" data-id="docu-code" title="Select code"></i>
    <pre><code id="docu-code" class="javascript">$('#canvas').canvasAnimation({
    steps: [
        {
            addClass: '',    // adds one or more classes to #canvas ('foo bar' adds 2 classes)
            removeClass: '', // remove one or more classes from #canvas ('foo bar' removes 2 classes)
            duration: 800    // duration of this step (milliseconds)
        }
    ],
    timeout: 0, // 0 = starts immediately the first step (milliseconds)
    reset_duration: 500, // time it takes to reset all animations (milliseconds)
    infinity: true, // if true: plays animation infinity
    autoplay: true, // if true: plays animation instantly
    controls: true, // if true: adds controls to canvas
    controls_fa: null, // fontawesome version (4 or 5)
    controls_wrapper: '.controls', // class of the controls wrapper
    step_backward_button: '.step-backward', // class of step backward button
    play_button: '.play', // class of play button
    pause_button: '.pause', // class of pause button
    reset_button: '.reset', // class of reset button
    step_forward_button: '.step-forward', // class of step forward button
    fullscreen_button: '.fullscreen', // class of fullscreen button
    class_done: 'done', // is set if the animation is done
    class_wait: 'wait', // is set if autoplay: false and animation is never played or user clicked on reset button
    class_forward: 'forward', // is set if user clicked step-forward
    class_backward: 'backward', // is set if user clicked step-backward
    class_wrap: 'canvas-animation',
    controls_template:
        '&lt;div class="controls"&gt;' +
            '&lt;div class="step-backward #STEPBACKWARD#"&gt;&lt;/div&gt;' +
            '&lt;div class="play #PLAY#"&gt;&lt;/div&gt;' +
            '&lt;div class="pause #PAUSE#"&gt;&lt;/div&gt;' +
            '&lt;div class="reset #RESET#"&gt;&lt;/div&gt;' +
            '&lt;div class="step-forward #STEPFORWARD#"&gt;&lt;/div&gt;' +
            '&lt;div class="fullscreen #FULLSCREEN#"&gt;&lt;/div&gt;' +
        '&lt;/div&gt;',
    callback_play: null, // called before first animation step
    callback_done: null, // called after last animation step
    callback_wait: null  // called if class_wait was added
});</code></pre>
</div>