<div class="code-wrap">
    <div class="code-icon" data-toggle="tooltip" data-placement="left" data-id="la-code" title="Select code"><i class="fas fa-code" aria-hidden="true"></i></div>
    <div class="code-lines"></div>
    <pre><code id="la-code" class="css">#love.ca-1 .square.red {
  left: 0;
  width: 100%;
  height: 50%;
}

#love.ca-1 .square.green {
  top: 50%;
  width: 50%;
  height: 50%;
}

#love.ca-1 .square.blue {
  top: 50%;
  width: 50%;
  height: 50%;
}

#love.ca-2 .square.red {
  top: 41.2%;
  left: 45%;
  width: 5%;
  height: 8.8%;
}

#love.ca-2 .square.green {
  top: 50%;
  right: 47.5%;
  width: 5%;
  height: 8.8%;
}

#love.ca-2 .square.blue {
  top: 41.2%;
  left: 50%;
  width: 5%;
  height: 8.8%;
}

#love.ca-3 .square.red {
  left: 44%;
  border-radius: 100px;
}

#love.ca-3 .square.green {
  background-color: red;
  right: 47.5%;
  top: 47.5%;
  transform: rotate(45deg);
}

#love.ca-3 .square.blue {
  left: 51%;
  background-color: red;
  border-radius: 100px;
}

#love.ca-4 .square.green:after {
  width: 60%;
}

#love.ca-4 .square.green:before {
  height: 60%;
}

#love.ca-4 .label {
  opacity: 1;
}

@-webkit-keyframes hue {
  from {
    -webkit-filter: hue-rotate(0deg);
  }

  to {
    -webkit-filter: hue-rotate(-360deg);
  }
}</code></pre>
</div>