<div class="code-wrap">
    <div class="code-icon" data-toggle="tooltip" data-placement="left" data-id="ls-code" title="Select code"><i class="fas fa-code" aria-hidden="true"></i></div>
    <div class="code-lines"></div>
    <pre><code id="ls-code" class="javascript">// jQuery.noConflict();
(function($) {
    $(document).ready(function() {
        $('#love').canvasAnimation(loveConfig);
    });
})(jQuery);

var loveConfig = {
    autoplay: true,
    infinite: false,
    useIcons: true,
    editor: {
        enable: false
    },
    steps: [
        {
            addClass: 'ca-1',
            duration: 800
        },
        {
            addClass: 'ca-2',
            duration: 800
        },
        {
            addClass: 'ca-3',
            duration: 800
        },
        {
            addClass: 'ca-4',
            duration: 500
        }
    ]
};</code></pre>
</div>