<div class="code-wrap">
    <i class="fa fa-code copy-code transition" aria-hidden="true" data-toggle="tooltip" data-placement="left" data-id="lh-code" title="Select code"></i>
    <div class="code-lines"></div>
    <pre><code id="lh-code" class="html">&lt;!DOCTYPE html>
&lt;html&gt;
    &lt;head&gt;
        &lt;title&gt;Spread Love&lt;/title&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"&gt;

        &lt;link rel="stylesheet" href="css/jquery.canvas-animation.css"&gt;
        &lt;link rel="stylesheet" href="css/love-canvas.css"&gt;
        &lt;link rel="stylesheet" href="css/love-animation.css"&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div id="love" class="canvas-ratio-16by9"&gt;
            &lt;div class="square red"&gt;&lt;/div&gt;
            &lt;div class="square green"&gt;&lt;/div&gt;
            &lt;div class="square blue"&gt;&lt;/div&gt;
            &lt;div class="label"&gt;spread love&lt;/div&gt;
        &lt;/div&gt;
        &lt;script src="js/jquery.js"&gt;&lt;/script&gt;
        &lt;script src="js/jquery.canvas-animation.js"&gt;&lt;/script&gt;
        &lt;script src="js/scripts.js"&gt;&lt;/script&gt;
    &lt;/body&gt;
&lt;/html&gt;</code></pre>
</div>