<div id="season" class="jca-ratio-16by9">
    <div class="spring">
        <!--
        <i class="fas fa-dove"></i>
        <i class="fas fa-frog"></i>
        -->
    </div>
    <div class="summer">
        <duv class="sun"><i class="fas fa-sun"></i></duv>
        <div class="ground"></div>
        <div class="net"><i class="fas fa-minus" data-fa-transform="rotate-90"></i></div>
        <div class="umbrella umbrella-1"><i class="fas fa-square-full" data-fa-mask="fas fa-umbrella-beach" data-fa-transform="down-16.25 grow-5"></i></div>
        <div class="umbrella umbrella-2"><i class="fas fa-square-full" data-fa-mask="fas fa-umbrella-beach" data-fa-transform="down-16.25 grow-5"></i></div>
        <div class="person person-1"><i class="fas fa-running"></i></div>
        <div class="person person-2"><i class="fas fa-running fa-flip-horizontal"></i></div>
        <div class="volleyball">
            <span class="fa-layers fa-fw">
                <i class="fas fa-circle"></i>
                <i class="fas fa-volleyball-ball" style="color: white;"></i>
            </span>
        </div>
        <!--
        <i class="fas fa-futbol"></i>
        <i class="fas fa-water"></i>
        <i class="fas fa-fish"></i>
        -->
    </div>
    <div class="fall">
        <div class="ground"></div>
        <div class="rain">
            <?php
            $left = 0;
            for ($i = 0; $i <= 15; $i++) {
                for ($h = 0; $h <= 15; $h++) {
                    $left = $h;
                    
                    if ($i % 2 === 0) {
                        $left = $h + .5;
                    }
                    
                    echo '<i class="fas fa-tint" data-fa-transform="rotate-330" style="left:' . ($left * 10) . '%;top:' . ($i * 10) . '%;"></i>';
                }
            }
            ?>
        </div>
        <div class="clouds">
            <?php
            for ($i = 0; $i <= 25; $i++) {
                echo '<i class="fas fa-cloud"  style="z-index:' . ($i % 2) . ';"></i>';
            }
            ?>
        </div>
        <div class="umbrella"><i class="fas fa-umbrella"></i></div>
        <div class="wind"><i class="fas fa-wind"></i></div>
        <!--
        <i class="fas fa-leaf"></i>
        -->
    </div>
    <div class="winter">
        <div class="ground"></div>
        <div class="tree"><i class="fas fa-tree"></i></div>
        <div class="crow crow-1"><i class="fas fa-crow"></i></div>
        <div class="crow crow-2"><i class="fas fa-crow fa-flip-horizontal"></i></div>
        <div class="bell bell-1"><i class="fas fa-bell"></i></div>
        <div class="bell bell-2"><i class="fas fa-bell"></i></div>
        <div class="cloud-1"><i class="fas fa-cloud"></i></div>
        <div class="star-1"><i class="fas fa-star"></i></div>
        <div class="gift-1"><i class="fas fa-gift"></i></div>
        <div class="gift-2"><i class="fas fa-gift"></i></div>
        <duv class="sun"><i class="fas fa-sun"></i></duv>
        <?php
        for ($i = 1; $i <= 5; $i++) {
            echo '<div class="flakes flakes-' . $i . '">';
            for ($h = 1; $h <= 15; $h++) {
                echo '<i class="far fa-snowflake"></i>';
            }
            echo '</div>';
        }
        ?>
        <div class="candle candle-1">
            <div class="wax"></div>
            <i class="fas fa-fire"></i>
        </div>
        <div class="candle candle-2">
            <div class="wax"></div>
            <i class="fas fa-fire"></i>
        </div>
    </div>
</div>
