<div id="season" class="jca-ratio-16by9">
    <div class="winter">
        <div class="ground"></div>
        <div class="tree"><i class="fas fa-tree"></i></div>
        <div class="crow crow-1"><i class="fas fa-crow"></i></div>
        <div class="crow crow-2"><i class="fas fa-crow fa-flip-horizontal"></i></div>
        <div class="bell bell-1"><i class="fas fa-bell"></i></div>
        <div class="bell bell-2"><i class="fas fa-bell"></i></div>
        <div class="cloud-1"><i class="fas fa-cloud"></i></div>
        <div class="star-1"><i class="fas fa-star"></i></div>
        <div class="gift-1"><i class="fas fa-gift"></i></div>
        <div class="gift-2"><i class="fas fa-gift"></i></div>
        <duv class="sun"><i class="fas fa-sun"></i></duv>
    </div>
</div>
