<div id="twitch" class="jca-ratio-16by9">
    <div class="logo">
        <div class="background-top"></div>
        <div class="background-center"></div>
        <div class="background-bottom"></div>
        <div class="background-tip">
            <div class="bg-tip"></div>
        </div>
        <div class="foreground-top"></div>
        <div class="foreground-bottom">
            <div class="fg-bottom"></div>
        </div>
        <div class="foreground-tip">
            <div class="fg-tip"></div>
        </div>
        <div class="eye left"></div>
        <div class="eye right"></div>
    </div>
</div>
