<!DOCTYPE html>
<html>
    <head>
        <title>Canvas Animation</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="theme-color" content="#212121">
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
        <link href="css/styles.css" rel="stylesheet"/>
    </head>
    <body>
        <?php include __DIR__ . '/../' . $template . '.phtml'; ?>
        <script type="text/javascript" src="js/scripts.js"></script>
    </body>
</html>