<div class="container">
    <div class="row">
        <div class="col-12 py-3">
            <h1 class="text-center pb-3">
                InsanityMeetsHH - Canvas Animation
                <a href="https://github.com/InsanityMeetsHH/jquery-canvas-animation"><i class="fab fa-github"></i></a>
            </h1>

            <ul class="nav nav-tabs" id="page-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#love-tab" role="tab" aria-controls="love-tab" aria-selected="true">Spread Love</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#twitch-tab" role="tab" aria-controls="twitch-tab" aria-selected="false">Twitch</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#docu-tab" role="tab" aria-controls="docu-tab" aria-selected="false">Docu</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-12 pb-3">
            <div class="tab-content pt-3">
                <div class="tab-pane fade show active" id="love-tab" role="tabpanel" aria-labelledby="love-tab">
                    <div id="love" class="canvas-ratio-16by9">
                        <div class="square red"></div>
                        <div class="square green"></div>
                        <div class="square blue"></div>
                        <div class="label">spread love</div>
                    </div>

                    <ul class="nav nav-tabs pt-3" id="love-source" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#love-html-tab" role="tab" aria-controls="love-html-tab" aria-selected="true">HTML</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#love-js-tab" role="tab" aria-controls="love-js-tab" aria-selected="false">scripts.js</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#love-dcss-tab" role="tab" aria-controls="love-dcss-tab" aria-selected="false">love-canvas.css</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="tab" href="#love-acss-tab" role="tab" aria-controls="love-tab" aria-selected="false">love-animation.css</a>
                        </li>
                    </ul>
                    <div class="tab-content pt-3">
                        <div class="tab-pane fade show active" id="love-html-tab" role="tabpanel" aria-labelledby="love-html-tab">
                            <?php include 'partials/love-html.phtml'; ?>
                        </div>
                        <div class="tab-pane fade" id="love-js-tab" role="tabpanel" aria-labelledby="love-js-tab">
                            <?php include 'partials/love-scripts.phtml'; ?>
                        </div>
                        <div class="tab-pane fade" id="love-dcss-tab" role="tabpanel" aria-labelledby="love-dcss-tab">
                            <?php include 'partials/love-canvas.phtml'; ?>
                        </div>
                        <div class="tab-pane fade" id="love-acss-tab" role="tabpanel" aria-labelledby="love-acss-tab">
                            <?php include 'partials/love-animation.phtml'; ?>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="twitch-tab" role="tabpanel" aria-labelledby="twitch-tab">
                    <div id="twitch" class="canvas-ratio-16by9">
                        <div class="logo">
                            <div class="background-top"></div>
                            <div class="background-center"></div>
                            <div class="background-bottom"></div>
                            <div class="background-tip">
                                <div class="bg-tip"></div>
                            </div>
                            <div class="foreground-top"></div>
                            <div class="foreground-bottom">
                                <div class="fg-bottom"></div>
                            </div>
                            <div class="foreground-tip">
                                <div class="fg-tip"></div>
                            </div>
                            <div class="eye left"></div>
                            <div class="eye right"></div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="docu-tab" role="tabpanel" aria-labelledby="docu-tab">
                    <?php include 'partials/documentation.phtml'; ?>
                </div>
            </div>
        </div>
    </div>
</div>